[package]
name = "alloc_mem"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
clap_complete = "4.5.44"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34+deprecated"
